### ISSUE TITLE
[Other] Documentation Updates

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#158]
I think it would be important to comb over the documentation to make it as effective as possible.

This is a running list of planned doc changes:

- [x] Consolidate the "Contributing" instructions. Right now someone wanting to contribute would read any of [contributing.rst](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docs/contributing.rst), [extending.rst](https://github.com/paperless-ngx/paperless-ngx/blob/main/docs/extending.rst), and [CONTRIBUTING.md](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md) #462 
  - [x] Removing `contributing.rst` (CONTRIBUTING.md integrates better with github)
  - [x] Moving technical details of now removed `contributing.rst` into `extending.rst`
  - [ ] Better linking to `extending.rst`from CONTRIBUTING.md
  - [x] Add translation instructions to CONTRIBUTING.md #108 
- [ ] Clarify the effect of docker volumes on config: https://github.com/paperless-ngx/paperless-ngx/issues/153#issuecomment-1051262289
- [ ] In [administration](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups), verify backup strategies and include note about docker volumes vs host mounts #153 
- [ ] Emphasize importance backups in install guide, link to relevant docs. 
- [ ] Copy docs from `configuration.rst` to `paperless.conf.example` #99
- [x] Move "Migrating from Paperless to Paperless-ng" from `README.md` to docs https://github.com/paperless-ngx/paperless-ngx/pull/147#issuecomment-1050901371
- [ ] Use "script" and "systemd unit" consistently #18 
- [ ] Beta Test Plan: list of things to try and a way to report results for thorough release testing

As issues from users start to pour in after #98 I imagine there will be more changes to make. Please let me know if there are more changes to add/discuss.

**Comment by shamoon** [comment]
Great call. So does everything goes into Contributing.md? We can probably move translation stuff into there too, and the README just has a very brief thing and links to that. IMHO readme should be short(-ish) and sweet

**Comment by qcasey** [comment]
Yes good idea!

**Comment by shamoon** [comment]
@gador please provide readthedocs access to others here. I have same username. Docs are currently pointing to dev and outdated

**Comment by gador** [comment]
sure thing. I just added you. If anyone else needs to be added, please provide the username :+1:

**Comment by gador** [comment]
Btw, shouldn't dev be the latest development? This is why I pointed the docs not to main but to dev..

**Comment by shamoon** [comment]
I think docs should only reflect what has been released, which should be main. In the future we should consider putting pure documentation changes directly into main and changes that have to do with un-released features etc into dev.

Thanks so much, I'll get it updated!

**Comment by qcasey** [comment]
> sure thing. I just added you. If anyone else needs to be added, please provide the username +1

Thanks for that! If there's no limit, could you add me as well?  qcasey

**Comment by shamoon** [comment]
> Thanks for that! If there's no limit, could you add me as well? qcasey

Added.

**Comment by qcasey** [comment]
Wait, are these done? I can't find the relevant commits

**Comment by shamoon** [comment]
Oh sorry I thought so! [reopening]

**Comment by qcasey** [comment]
Ok thanks. This will be my pet project once I'm back, but if anyone would like to jump in and take care of a few that'd be appreciated too.

**Comment by shamoon** [comment]
> Ok thanks. This will be my pet project once I'm back, but if anyone would like to jump in and take care of a few that'd be appreciated too.

Oh ok cool. I can probably knock off something.
