### ISSUE TITLE
[BUG] File tasks screen very slow to dismiss when task list is long

### ISSUE THREAD

**Issue by tcabanski** [paperless-ngx/paperless-ngx#5499]
### Description

I am running a huge import and the task list has almost 20K tasks in it as a result. When I dismiss a single task, it appears to take more than a second before I can dismiss another. This is because the entire task list is reloaded after each dismissal, which takes just over 900ms. It would be OK if the app simply assumed dismiss works and deletes the item from the local list before calling for the update of the task list, which appears to be async (I'm not looking at the code here).

Anyway, this probably also impacts performance overall since "auto refresh on" is the default and I would assume tasks are being loaded in the background periodically. I'll file another issue on this part.

### Steps to reproduce

1. Have 10K plus tasks in the task list
2. Dismiss a document
3. Immediately dismiss another
4

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.4.0

### Host OS

Windows

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Well, that's a massive amount of tasks.  I'm not sure this is really a bug at all or just a feature request.

**Comment by shamoon** [comment]
Yea I’m not sure this is really actionable by us. You create 20k tasks at once I’m not surprised the app has some trouble with that. There’s a button to select and dismiss all.
