### ISSUE TITLE
[BUG] The task list can be viewed via the API, even if the permissions do not allow this

### ISSUE THREAD

**Issue by beposec** [paperless-ngx/paperless-ngx#6957]
### Description

If I deactivate the ‘Task List’ permission, users can no longer see the task list via the web interface. However, users can still see the task list via the URL https://paperless/api/tasks/.

### Steps to reproduce

1. Set the PaperlessTask Permission to disabled.
2. Open https://paperless/api/tasks/

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.9.0

### Host OS

Debian 12

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.9.0",
    "server_os": "Linux-6.1.0-17-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 105087164416,
        "available": 90800820224
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "account.0009_emailaddress_unique_primary_email",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-11T00:00:01.014274+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-11T06:05:00.217138Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
